export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';
export const CHANGE_FROM_CURRENCY = 'CHANGE_FROM_CURRENCY';
export const CHANGE_TO_CURRENCY = 'CHANGE_TO_CURRENCY';
export const INVERSE_CURRENCY = 'INVERSE_CURRENCY';
export const FETCH_START = 'FETCH_START';
export const FETCH_DATA = 'FETCH_DATA';
